sudo: false
language: scala
scala:
  - 2.11.11
  - 2.12.4
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker pull ruo91/arcus
  - docker run -d --name="arcus-admin" -h "arcus" arcus-admin
  - docker run -d --name="arcus-memcached-1" -h "memcached-1" arcus-memcached
script:
  - sbt +test
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print