sudo: false
language: scala
scala:
  - 2.12.0
jdk:
  - oraclejdk8
services:
  - memcached
  - redis
script:
  - sbt +test
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
