sudo: false
language: scala
scala:
  - 2.11.11
  - 2.12.8
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker pull ikhoon/arcus-dockerfile
  - docker run -d -p 2181:2181 -p 11212:11212 -p 11213:11213 ikhoon/arcus-dockerfile
script:
  - sbt +test
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
